name: OniaOpenCharmRun2ULenv
channels:
  - conda-forge
dependencies:
  - python == 3.8
  - xrootd
  - pip
  - matplotlib
  - boost-histogram >=0.10.0
  - jupyterlab >=2
  - uncertainties
  - nodejs
  - pip:
    - coffea
    - hist >=2.0.0a5
    - mplhep >=0.1.27
    - pyyaml
    